pipeline {
  agent any

  stages {
    stage("Clean") {
        steps {
            script {
                withDotNet(sdk: '.NET 8') {
                    echo "Cleaning project..."
                    dotnetClean sdk: '.NET 8'
                }
            }
        }
    }

    stage("Add source") {
        steps {
            script {
                withDotNet(sdk: '.NET 8') {
                    withCredentials([string(credentialsId: 'addSourceCmd', variable: 'addSourceCmd')]) {
                        try {
                            echo "Adding private sources"
                            sh '$addSourceCmd'
                        } catch (err) {
                            echo "Source already exists"
                        }
                    }
                }
            }
        }
    }

    stage("Restore Project") {
        steps {
            script {
                withDotNet(sdk: '.NET 8') {
                    echo "Restoring Project"
                    dotnetRestore sdk: '.NET 8'
                }
            }
        }
    }

    stage("Unit Tests") {
        steps {
            script {
                withDotNet(sdk: '.NET 8') {
                    echo "Running Unit Tests"
                    dotnetTest sdk: '.NET 8'
                }
            }
        }
    }

    stage ("Build") {
        steps {
            script {
                withDotNet(sdk: '.NET 8') {
                    echo "Building..."
                    dotnetBuild configuration: 'Release', noRestore: true, sdk: '.NET 8'
                }
            }
        }
    }

    stage ("Docker") {
        steps {
            script {
                echo "Building docker image"
                if (env.BRANCH_NAME == "main") {
                    sh "docker build -t gotravelcon:latest -f 'Project Files/Dockerfile.prod' . --progress=plain"
                    sh "docker save -o gotravelcon.tar gotravelcon:latest"
                }

                if (env.BRANCH_NAME == "develop") {
                    sh "docker build -t gotravelcondev:latest -f 'Project Files/Dockerfile.dev' . --progress=plain"
                    sh "docker save -o gotravelcon_dev.tar gotravelcondev:latest"
                }
            }
        }
    }

    stage("Publish") {
        steps {
            script {
                if (env.BRANCH_NAME == 'main') {
                    sshPublisher(
                        publishers: [
                            sshPublisherDesc(
                                configName: 'VPS',
                                verbose: true,
                                transfers: [
                                    sshTransfer(
                                        sourceFiles: "gotravelcon.tar",
                                        remoteDirectory: 'GoTravel.Connector',
                                        execTimeout: 600000,
                                        execCommand: './_scripts/gtcon.sh'
                                    )
                                ]
                            )
                        ]
                    )
                }

                if (env.BRANCH_NAME == 'develop') {
                    sshPublisher(
                        publishers: [
                            sshPublisherDesc(
                                configName: 'VPS',
                                verbose: true,
                                transfers: [
                                    sshTransfer(
                                        sourceFiles: "gotravelcon_dev.tar",
                                        remoteDirectory: 'GoTravel.Connector.Dev',
                                        execTimeout: 600000,
                                        execCommand: './_scripts/gtcon_dev.sh'
                                    )
                                ]
                            )
                        ]
                    )
                }
            }
        }
    }
  }
}